# Generated by Django 3.0.3 on 2020-02-19 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_api', '0002_auto_20200218_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(max_length=45, verbose_name='店铺名称'),
        ),
        migrations.AlterUniqueTogether(
            name='store',
            unique_together={('owner', 'name')},
        ),
    ]
